### ISSUE TITLE
Players kicked due to Community Ban but no bans in player steam

### ISSUE THREAD

**Issue by crashzk** [azalty/sm-no-dupe-account#28]
**Describe the bug**
Players being kicked off the servers, however it has all requirements.

**Error logs**
Checking the `console.log` log I found this.
```
L 10/21/2021 - 18:41:33: [no_dupe_account.smx] Playtime request failed!
L 10/21/2021 - 18:41:33: [no_dupe_account.smx] Steam Bans request failed!
L 10/21/2021 - 18:41:36: [no_dupe_account.smx] Steam Bans request failed!
L 10/21/2021 - 18:41:36: [no_dupe_account.smx] Playtime request failed!
L 10/21/2021 - 18:43:27: [no_dupe_account.smx] Steam Bans request failed!
L 10/23/2021 - 17:17:28: [no_dupe_account.smx] Playtime request failed!
L 10/26/2021 - 20:04:12: [no_dupe_account.smx] Playtime request failed!
L 10/26/2021 - 20:04:32: [no_dupe_account.smx] Playtime request failed!

Dropped ⛧GGsixxx⛧ from server: Contas com Ban Comunidade são proibidas de se conectar ao servidor
Dropped 路卡思 Lucas from server: Contas com Ban Comunidade são proibidas de se conectar ao servidor
Dropped transei nao gostei from server: Contas com Ban Comunidade são proibidas de se conectar ao servidor
Dropped ♰ɴɪᴄᴋシ from server: Contas com Ban Comunidade são proibidas de se conectar ao servidor
Dropped JcZip from server: Contas com Ban Comunidade são proibidas de se conectar ao servidor

L 11/02/2021 - 20:02:30: [no_dupe_account.smx] Steam Bans request failed!
Dropped XeryuS from server: Contas com Ban Comunidade são proibidas de se conectar ao servidor

PutClientInServer: no info_player_start on level

L 11/02/2021 - 20:02:35: [no_dupe_account.smx] Steam Bans request failed!
L 11/02/2021 - 20:02:43: [no_dupe_account.smx] Steam Bans request failed!

PutClientInServer: no info_player_start on level

L 11/02/2021 - 20:02:52: [no_dupe_account.smx] Steam Bans request failed!
L 11/02/2021 - 20:02:52: [no_dupe_account.smx] Playtime request failed!
L 11/02/2021 - 20:02:55: [no_dupe_account.smx] Steam Bans request failed!
```
![image](https://user-images.githubusercontent.com/32937653/139965208-4c0ddb52-8efb-45fc-adec-7a6a45516349.png)

This error occurred as soon as Steam Tuesday's maintenance started.

https://steamstat.us/

Could it be because of this steam maintenance?

**Comment by crashzk** [comment]
I'm using the version:
```
"No Dupe Account" (1.5.0 Beta 2) by azalty/rlevet
```

**Comment by azalty** [comment]
> This error occurred as soon as Steam Tuesday's maintenance started.

Yep, good guess, noticed this too on my server.

While Steam is in maintenance, requests will fail.

EDIT: The quoted text below is FALSE!

> _When the API doesn't return us anything while asking for a Steam profile, it means that the profile is community banned, but in the case there is a maintenance or a problem, it will also do the same thing._

I'll take a look to see if there's any way to tell that someone is community banned. Else, I'll have to implement something that let people go through when the time is around the weekly maintenance, unless there's an API call that can tell us that a maintenance is in progress.

**Comment by azalty** [comment]
By the way, this issue should also affect stable releases, and is not because of the beta. Thanks for specifying the version you're using though!

**Comment by azalty** [comment]
The thing that is weird is that when the Steam Bans request fails, it shouldn't kick people for having a Community Ban, since that only happens when the request works but returns less infos than normal.

It could be possible that the API still answers, but with less informations than normal. Perhaps, it returns something different than someone with a community ban, which could allow us to fix that.

The thing is, how can I test if there's no maintenance in progress?? :(

**Comment by azalty** [comment]
By reading the code, I think the API doesn't return the CommunityBanned field when Steam is in maintenance, making the plugin think the user is community banned while it isn't.

I added a new check to verify that the field exists and is either set to true or false.

The API might actually return true, or do something else, but I think it answers a blank response, or something similar.
We'll see how it goes. In the worst case, this fix will just be useless, not harmful.

**Comment by crashzk** [comment]
Good, I will be testing this new version and return here with feedback.

**Comment by crashzk** [comment]
@azalty just feedback.

I keep getting error in **`console.log`** logs still:
```
L 11/05/2021 - 22:44:53: [no_dupe_account.smx] Steam Bans request failed!
L 11/05/2021 - 22:44:53: [no_dupe_account.smx] Playtime request failed!
L 11/05/2021 - 22:46:36: [no_dupe_account.smx] Steam Bans request failed!
L 11/05/2021 - 22:46:47: [no_dupe_account.smx] Steam Bans request failed!
L 11/05/2021 - 22:48:05: [no_dupe_account.smx] Steam Bans request failed!
L 11/05/2021 - 22:49:58: [no_dupe_account.smx] Steam Bans request failed!
L 11/05/2021 - 22:49:58: [no_dupe_account.smx] Playtime request failed!
```
Print from this exact moment, showed error after I changed the map.

![image](https://user-images.githubusercontent.com/32937653/140593931-ad00781a-39cb-48f4-b8a1-ab0b156863cb.png)

Apparently it's showing less, but it still shows.

**Comment by azalty** [comment]
@crashzk this should actually be in #12 

The fix I wrote only fixes players being kicked for having a community ban when they didn't. This issue seemed to appear with Steam maintenances.

I still don't know why requests fail from time to time.
Here, the only request that seem to fail is the Steam Bans one. My guess is that it was the only request type that was done, since Steam Bans values aren't stored into the database, and thus must be retrieved from the Steam API everytime a player joins.

Again, it could be caused by the fact we do all requests at the same time, it might also be because you're getting rate-limited, or the Steam API could have an error.

The truth is, without extensive testing, or help of someone that has knowledge about that, we won't get the cause of this problem.

So yea, this problem isn't related to this issue, but thanks for notifying me :)

**Comment by azalty** [comment]
Forgot to put 1.5.0 Beta 3 .smx (plugin) file in the right folder, this is now fixed in 1.5.0 Beta 4 (which also adds logging)
https://github.com/azalty/sm-no-dupe-account/commit/0fd834b70e7254aad6a2d90ed64a2c8ed8e2d42b

**Comment by crashzk** [comment]
So I had noticed that. I even compiled it to the new version and still nothing.

In any case I will send this new version and I'll be back here, thanks for the time.

**Comment by crashzk** [comment]
@azalty I sent it, having more information return here.

For now I would like to clear a question, this problem may be related to Steam/CSGO or even SourceMod?

I ask because I realized that when this errors occurs, other plugins also have a delay, errors. Example, my servers have the plugin **SWGM**: https://github.com/ZK-Servidores/SWGM

It works perfectly, but there are times when I change the map I have to wait a few rounds for the plugin to start blocking the commands.

Same thing with the **VIP Core**, there are times when I change maps, there are more times, some rounds also that I have to wait to read the privileges.

From what I could see this happens with most plugins that use MySQL database, at least with me. But I've also noticed the same delay, time to work on plugins that don't use any kind of database, example **ServerAdvertisement3**: https://github.com/ESK0/ServerAdvertisement3

There are times that after I change the map it only starts sending messages after all the plugins I mentioned above start working, a few rounds later.

Anyway, I'm starting to think it might be something related to SourceMod itself. Or would I be completely wrong?

**Comment by azalty** [comment]
Your server performances might be bad.

Some plugins might do too many SQL queries and thus block all the other ones

Using a SQLite database helps.

For NDA, 1 query is done per join, 1 query per disconnect. As simple as that.

**Comment by crashzk** [comment]
Just a feedback, until yesterday 11/06/2021 still appeared some error logs. But as I don't remember the right time I sent it, I'm discarding it, thinking it's due to the old version.

For now I believe that these issues can be closed, if the problem occurs again I open a new one.

Thanks for the hour.

**Comment by azalty** [comment]
The issue you reported is caused by the Steam maintenance, wait for the next maintenance to see if it's fixed.

If web requests fail outside of Steam maintenances, please comment on #12

**Comment by crashzk** [comment]
@azalty today during steam maintenance it returned the error in **`console.log`**.

![image](https://user-images.githubusercontent.com/32937653/141040933-843366c5-0c69-4b4a-a28a-8f2950d981ad.png)

Most recent are from today 9/11, 06th and older are before submitting the changes you made.

**Comment by azalty** [comment]
Any news regarding this @crashzk?

**Comment by azalty** [comment]
> @azalty today during steam maintenance it returned the error in **`console.log`**.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/32937653/141040933-843366c5-0c69-4b4a-a28a-8f2950d981ad.png)
> 
> 
> 
> Most recent are from today 9/11, 06th and older are before submitting the changes you made.

**This issue is about player being kicked for having a community ban while they actually aren't banned** (And not about requests failing with Status Code 0). Was any player kicked for "community ban" during those fails/Steam Maintenance?

The Status code 0 request fails are greatly reduced/gone in the latest Beta version, you should consider switching to it if you're not already using it (I'm fairly sure it is stable too).

**Comment by crashzk** [comment]
I will check if I have the latest version of the Beta version.

But from what I've noticed recently, no one is being expelled anymore due to verification errors, I believe it could be closing these issues, anything I'll contact you again.

**Comment by azalty** [comment]
> I will check if I have the latest version of the Beta version.
> 
> But from what I've noticed recently, no one is being expelled anymore due to verification errors, I believe it could be closing these issues, anything I'll contact you again.

Let that open until we confirm this is properly handled. A specific error message should show.
Since this isn't a major bug in itself, I think I'll release 1.5.0 Stable soon, even if this issue is not confirmed as fixed yet.

**Comment by azalty** [comment]
Potential fix added in the 1.5.0 stable release.

If it worked, please send logs of it :)
It it doesn't, please tell me :)

**Comment by crashzk** [comment]
I believe this issue can be closed, I have not had any more issues related to this error.

**Comment by azalty** [comment]
As long as you don't have a custom error message, it means the problem didn't happen

I want to know the final word of this!!

**Comment by crashzk** [comment]
Oops sorry for the delay **@azalty**.

I believe this issues can be closed, I didn't have any more custom errors, as I mentioned here in the issues: https://github.com/azalty/sm-no-dupe-account/issues/31

Anyway, I believe that both issues can be closed, the errors/bugs seem to have been resolved.

**Comment by azalty** [comment]
Seems like a rare bug. I'll keep the fix and custom error message in case it still happens.

If anyone encounters this problem, re-open this issue :)

I'll mark it as fixed because the error is now handled.
